spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/online_store_dev
    username: postgres
    password: husniddin
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false

logging:
  level:
    husniddin.online_store: DEBUG
    org.hibernate.SQL: OFF
    org.hibernate.orm.jdbc.bind: OFF
    org.hibernate.type.descriptor.sql: OFF
