spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/onlinest_database
    username: onlinest_database
    password: husniddin2003
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false

server:
  port: 8080

logging:
  level:
    root: WARN
    husniddin.online_store: INFO
  file:
    name: /var/log/online-store/app.log
